/**
 * Export Utilities
 *
 * Export chat conversations in multiple formats
 * Markdown, PDF, HTML, JSON, Share link
 */

import type { Message } from '@ai-sdk/react';

// ============================================================================
// MARKDOWN EXPORT
// ============================================================================

export function exportToMarkdown(messages: Message[], title?: string): string {
  const timestamp = new Date().toLocaleString();
  let markdown = '';

  // Header
  if (title) {
    markdown += `# ${title}\n\n`;
  }
  markdown += `*Exported: ${timestamp}*\n\n`;
  markdown += `---\n\n`;

  // Messages
  for (const message of messages) {
    const role = message.role === 'user' ? '**You**' : '**AI**';
    markdown += `### ${role}\n\n`;
    markdown += `${message.content}\n\n`;
    markdown += `---\n\n`;
  }

  return markdown;
}

// ============================================================================
// HTML EXPORT
// ============================================================================

export function exportToHTML(messages: Message[], title?: string): string {
  const timestamp = new Date().toLocaleString();

  let html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title || 'Chat Export'}</title>
  <style>
    body {
      font-family: system-ui, -apple-system, sans-serif;
      max-width: 800px;
      margin: 0 auto;
      padding: 2rem;
      background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
    }
    .header {
      text-align: center;
      margin-bottom: 2rem;
      padding-bottom: 1rem;
      border-bottom: 2px solid #667eea;
    }
    .message {
      margin-bottom: 1.5rem;
      padding: 1rem;
      border-radius: 1rem;
      box-shadow: 0 4px 6px rgba(0,0,0,0.1);
    }
    .user {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      margin-left: auto;
      max-width: 80%;
    }
    .assistant {
      background: white;
      max-width: 80%;
    }
    .role {
      font-weight: bold;
      margin-bottom: 0.5rem;
      font-size: 0.875rem;
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }
    .content {
      line-height: 1.6;
      white-space: pre-wrap;
    }
    .footer {
      text-align: center;
      margin-top: 2rem;
      padding-top: 1rem;
      border-top: 1px solid #ddd;
      color: #666;
      font-size: 0.875rem;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>${title || 'Chat Conversation'}</h1>
    <p>Exported: ${timestamp}</p>
  </div>
  <div class="messages">`;

  for (const message of messages) {
    const roleClass = message.role === 'user' ? 'user' : 'assistant';
    const roleName = message.role === 'user' ? 'You' : 'AI Assistant';

    html += `
    <div class="message ${roleClass}">
      <div class="role">${roleName}</div>
      <div class="content">${escapeHTML(message.content)}</div>
    </div>`;
  }

  html += `
  </div>
  <div class="footer">
    <p>Generated by UltraChat - ONE Platform</p>
  </div>
</body>
</html>`;

  return html;
}

function escapeHTML(text: string): string {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}

// ============================================================================
// JSON EXPORT
// ============================================================================

export function exportToJSON(messages: Message[], metadata?: Record<string, any>): string {
  const exportData = {
    version: '1.0',
    exportedAt: new Date().toISOString(),
    metadata: metadata || {},
    messages: messages.map(msg => ({
      id: msg.id,
      role: msg.role,
      content: msg.content,
      createdAt: msg.createdAt,
    })),
  };

  return JSON.stringify(exportData, null, 2);
}

// ============================================================================
// DOWNLOAD FILE
// ============================================================================

export function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ============================================================================
// CONVENIENCE FUNCTIONS
// ============================================================================

export function downloadMarkdown(messages: Message[], title?: string): void {
  const markdown = exportToMarkdown(messages, title);
  const filename = `chat-${Date.now()}.md`;
  downloadFile(markdown, filename, 'text/markdown');
}

export function downloadHTML(messages: Message[], title?: string): void {
  const html = exportToHTML(messages, title);
  const filename = `chat-${Date.now()}.html`;
  downloadFile(html, filename, 'text/html');
}

export function downloadJSON(messages: Message[], metadata?: Record<string, any>): void {
  const json = exportToJSON(messages, metadata);
  const filename = `chat-${Date.now()}.json`;
  downloadFile(json, filename, 'application/json');
}

// ============================================================================
// COPY TO CLIPBOARD
// ============================================================================

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (err) {
    console.error('Failed to copy to clipboard:', err);
    return false;
  }
}

export async function copyMarkdownToClipboard(messages: Message[], title?: string): Promise<boolean> {
  const markdown = exportToMarkdown(messages, title);
  return await copyToClipboard(markdown);
}

// ============================================================================
// SHARE LINK (Future implementation)
// ============================================================================

export function generateShareLink(messages: Message[]): string {
  // In production, this would upload to a backend and return a share URL
  // For now, return a data URL
  const json = exportToJSON(messages);
  const encoded = btoa(json);
  return `${window.location.origin}/chat/shared/${encoded}`;
}
